AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template builds out the environment
Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.

Resources:  
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: stack
         Value: development
#Outputs:
#  WebsiteURL:
#    Value: !Join 
#      - ''
#      - - 'http://'
#        - !GetAtt 
#          - ApplicationLoadBalancer
#          - DNSName
#        - /wordpress
#    Description: WordPress Website
