AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template builds out the environment
#Parameters:
#  VpcId:
#    Type: 'AWS::EC2::VPC::Id'
#    Description: VpcId of your existing Virtual Private Cloud (VPC)
#    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.

Resources:  
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.20.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: stack
         Value: development
       - Key: Name
         Value: Wordpress
  myRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: myVPC
      Tags:
      - Key: stack
        Value: development
      - Key: Name
        Value: Wordpress
  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.20.1.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
       - Key: stack
         Value: development
       - Key: Name
         Value: SubnetUSeast
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.20.2.0/24
      AvailabilityZone: "us-east-1b"
      Tags:
       - Key: stack
         Value: development
       - Key: Name
         Value: SubnetUSeast1b
#Outputs:
#  WebsiteURL:
#    Value: !Join 
#      - ''
#      - - 'http://'
#        - !GetAtt 
#          - ApplicationLoadBalancer
#          - DNSName
#        - /wordpress
#    Description: WordPress Website
